### PR TITLE
Make `onInitializeLayout` abstract

### PR DESCRIPTION
**Pull request by AlecStrong**
i want the IDE to just tell me how to build one of these, right now I find myself clicking into ContourLayout because I cant remember the method I'm supposed to override

### CODE REVIEW

**Comment by aerb** [comment]
I really go back and forth on this. I might actually kill `onInitializeLayout` for reasons I will go into later. But there are definitely two styles. Defining layout inline with the other view definitions - or separating the  layout to some other place. I have no strong stylistic argument for one or the other - but there is a technical reason I dislike `onInitializeLayout`.

**Comment by AlecStrong** [comment]
i'd be curious to hear more - essentially the thing i want to optimize for is intellij option-entering your way to the right API

**Comment by FAT32SHAMER** [comment]
I personally am in favour of there being one “correct” way of doing something to both make it simpler to implement as well as not leave ambiguity to new devs, but that’s just me

**Comment by AlecStrong** [comment]
As a point of reference iOS has `layoutSubviews` (https://developer.apple.com/documentation/uikit/uiview/1622482-layoutsubviews) which I also think would be a nicer name

Anyways my point with all this is it's super unintuitive if the parent class doesn't impose anything, having an abstract method means the IDE will tell you what method you need to use to do layouts. I'd also love if the applyLayout function was scoped to layoutSubviews to further that. There's plenty of alternative ways to accomplish it too but this seems like the most straightforward way

Also to answer your question Mario it's more of a design thing than anything

**Comment by carranca** [comment]
The reasoning sounds good to me - I might take a stab at exploring the scoping of `applyLayout` to `layoutSubviews` (do you want to rename it? I actually like the iOS name)

**Comment by dimsuz** [comment]
I may have found one use case where I **have** to use  `onInitializeLayout()`:

```kotlin
private val textView = TextView(context).apply {...}
private val backgroundView = View(context).apply {...}

fun onInitializeLayout() {
    backgroundView.applyLayout(
      x = matchXTo(textView, marginLeft = (-24).dip, marginRight = (-24).dip),
      y = topTo { textView.top() - 24.dip }.bottomTo { textView.bottom() + 24.dip }
    )

    textView.applyLayout(
      x = matchParentX(marginLeft = 24.dip, marginRight = 24.dip),
      y = topTo { parent.top() + 24.dip }
    )
}
```

Here we have a `textView` which is a simple `TextView` and around it we have it wrapped with `backgroundView` which draws an opaque background. Now if I'd went with the option where I call `applyLayout()` right where I declare `private val textView = TextView().apply {...}` this would require me to declare `textView` first and then `backgroundView` after it (otherwise compiler wouldn't see `textView` in `backgroundView`'s rules lambda. And this results in a drawing order where `backgroundView` is drawn on top of the `TextView` completely obscuring it.

So when the certain drawing order is needed and you declare rules in a way which requires view declarations down below having no `onInitializeLayout()` option would be a problem or one would need to invent something similar.

**Comment by dimsuz** [comment]
Oh, it turns out that this part in my description is wrong:
> otherwise compiler wouldn't see textView in backgroundView's rules lambda

Instead compiler gave a recursive type checking error. It can be fixed by specifying view type explicitly when declaring a property.

So disregard my comment.

**Comment by oldergod** [comment]
> but there is a technical reason I dislike onInitializeLayout.

@aerb yeah?

**Comment by aerb** [comment]
onInitiateLayout can be called during measurement phase or during window attach. It makes layout slightly less deterministic, which is why I'm not a fan.

**Comment by carranca** [comment]
We've had some discussions about this, and in light of @saket 's introduction of `layoutBy` I propose we either deprecate **or altogether remove** (since we're not 1.0-stable yet) `onInitializeLayout()`.

Any objections, concerns, alternatives?
@aerb @oldergod @dimsuz @saket @AlecStrong @FAT32SHAMER

**Comment by saket** [comment]
@carranca I'm okay with it but I know that some folks in our team prefer overriding the abstract function to layout children. We could encourage people to do it in their `init` block instead?

**Comment by carranca** [comment]
> @carranca I'm okay with it but I know that some folks in our team prefer overriding the abstract function to layout children. We could encourage people to do it in their `init` block instead?

I'd say we can, yeah. As @aerb pointed out, `onInitializeLayout()` makes things a bit deterministic, because you don't actually know what phase of the view's layout it's getting called in and might therefore lead you to make assumptions about the view's current measurements etc.

I think doing layout at initialization time (`private val myView = View(context).layoutBy {...`) or in `init` should satisfy everyone's preferences. People can still delegate to a separate method, but it won't be one provided by the library since the library provides no guarantees anyway?

Hoping to hear from more folks on this before taking action.

**Comment by carranca** [comment]
Closing this PR as it's been superseded by https://github.com/cashapp/contour/issues/77

**Pull request closed without merging**
