### PR TITLE
Fix YInt and YFloat compareTo() to take YInt/YFloat values

### PR DESCRIPTION
**Pull request by Orgmir**
Trying to compare to Y values will not work, since the type is declared wrongly.

### CODE REVIEW

**Comment by oldergod** [comment]
Thanks!

**Comment by JakeWharton** [comment]
Would be great to get some tests. Obviously there's a large area of the public API that isn't covered.

**Comment by dimsuz** [comment]
@aerb @saket Wanted to urge you to release this fix, we constantly  bump into it. Working around with extra `y1.toX() <= y2.toX()` and introduced our own `YInt.compareTo`, but IDE doesn't autoimport it, etc, etc, would be nice to have a release with it fixed (maybe a minor one?)

**Comment by saket** [comment]
Is using the SNAPSHOT an option in the meantime?

**Comment by dimsuz** [comment]
Yes, but I guess we can use our workarounds for now, just wanted to mention that this is an issue we often run into. In case you have a second thoughts on releasing in near future :slightly_smiling_face: 

I also want to express (again) how much I am enjoying contour, thanks to all involved! And productivity is also great, speed up compared to the "old-ways" is quite noticable!

**Comment by oldergod** [comment]
We'll be releasing within 2 weeks :+1:

**Comment by oldergod** [comment]
1.1.0 has been released.

**Pull request merged**
